#[odoo_servers]
#ec2-44-203-68-58.compute-1.amazonaws.com ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_python_interpreter=/usr/bin/python3

[web]
#ubuntu@54.197.187.46
#ubuntu@44.202.165.130
#ubuntu@98.89.3.253
#ubuntu@3.88.171.212
#ubuntu@34.207.152.49
#ubuntu@100.53.176.111


[all]
#store01 ansible_host=34.229.143.20 ansible_user=ubuntu ansible_ssh_private_key_file=/home/odoo/.ssh/id_rsa db_name=store01 db_user=odoo17 db_password=admin
#store02 ansible_host=100.31.154.207  ansible_user=ubuntu ansible_ssh_private_key_file=/home/odoo/.ssh/id_rsa db_name=store02_db db_user=odoo17 db_password=admin
store01 ansible_host=192.168.168.93 ansible_user=store3 ansible_become=true ansible_become_method=sudo ansible_ssh_private_key_file=/home/odoo/.ssh/id_rsa db_name=store1_db db_user=odoo17 db_password=admin
store02 ansible_host=192.168.168.190 ansible_user=odoo ansible_become=true ansible_become_method=sudo ansible_ssh_private_key_file=/home/odoo/.ssh/id_rsa db_name=store2_db db_user=odoo17 db_password=admin
